export const califications = [
  {
    name: 'Matemática',
    calification1: 18,
    calification2: 18,
    calification3: 18,
    calification4: null,
    average: null,
  },
  {
    name: 'Aritmética',
    calification1: 18,
    calification2: 18,
    calification3: 18,
    calification4: null,
    average: null,
  },
  {
    name: 'Literatura',
    calification1: 18,
    calification2: 18,
    calification3: 18,
    calification4: null,
    average: null,
  },
  {
    name: 'Física',
    calification1: 18,
    calification2: 18,
    calification3: 18,
    calification4: null,
    average: null,
  },
  {
    name: 'Química',
    calification1: 18,
    calification2: 18,
    calification3: 18,
    calification4: null,
    average: null,
  },
  {
    name: 'Educación física',
    calification1: 18,
    calification2: 18,
    calification3: 18,
    calification4: null,
    average: null,
  },
  {
    name: 'Geografía',
    calification1: 18,
    calification2: 18,
    calification3: 18,
    calification4: null,
    average: null,
  },
  {
    name: 'Historia',
    calification1: 18,
    calification2: 18,
    calification3: 18,
    calification4: null,
    average: null,
  },
]